<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="com.jbk.qa.testcases.LoginPageTest" tests="11" time="1.387" ignored="8" failures="3" timestamp="31 Dec 2019 08:05:36 GMT" skipped="0" hostname="SUBHASHA-PC" errors="0">
  <testcase name="verifyUrl" time="0.012" classname="com.jbk.qa.testcases.LoginPageTest">
    <failure type="java.lang.AssertionError" message="expected [file:///E:/Offline%20Website/index.html] but found [file:///E:/Offline%20Website/pages/examples/register.html]">
      <![CDATA[java.lang.AssertionError: expected [file:///E:/Offline%20Website/index.html] but found [file:///E:/Offline%20Website/pages/examples/register.html]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.jbk.qa.testcases.LoginPageTest.verifyUrl(LoginPageTest.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- verifyUrl -->
  <testcase name="verifyTitle" time="0.053" classname="com.jbk.qa.testcases.LoginPageTest"/>
  <testcase name="Login" time="0.308" classname="com.jbk.qa.testcases.LoginPageTest"/>
  <testcase name="verifyLinks" time="0.070" classname="com.jbk.qa.testcases.LoginPageTest"/>
  <testcase name="Login" time="0.383" classname="com.jbk.qa.testcases.LoginPageTest"/>
  <testcase name="verifyloginsesion" time="0.019" classname="com.jbk.qa.testcases.LoginPageTest">
    <failure type="java.lang.AssertionError" message="expected [Sign in to start your session] but found [Register a new membership]">
      <![CDATA[java.lang.AssertionError: expected [Sign in to start your session] but found [Register a new membership]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.jbk.qa.testcases.LoginPageTest.verifyloginsesion(LoginPageTest.java:66)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- verifyloginsesion -->
  <testcase name="verifyPlaceHolderUsername" time="0.026" classname="com.jbk.qa.testcases.LoginPageTest"/>
  <testcase name="verifyButtoncolor" time="0.170" classname="com.jbk.qa.testcases.LoginPageTest"/>
  <testcase name="verifyPlaceHolderPassword" time="0.023" classname="com.jbk.qa.testcases.LoginPageTest"/>
  <testcase name="Login" time="0.312" classname="com.jbk.qa.testcases.LoginPageTest"/>
  <testcase name="verifyApplicationTitle" time="0.011" classname="com.jbk.qa.testcases.LoginPageTest">
    <failure type="java.lang.AssertionError" message="expected [JavaByKiran | Log in] but found [JavaByKiran | Registration Page]">
      <![CDATA[java.lang.AssertionError: expected [JavaByKiran | Log in] but found [JavaByKiran | Registration Page]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.jbk.qa.testcases.LoginPageTest.verifyApplicationTitle(LoginPageTest.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- verifyApplicationTitle -->
  <testcase name="tearDown" classname="com.jbk.qa.base.TestBase">
    <skipped/>
  </testcase> <!-- tearDown -->
  <testcase name="tearDown" classname="com.jbk.qa.base.TestBase">
    <skipped/>
  </testcase> <!-- tearDown -->
  <testcase name="setup_Browser" classname="com.jbk.qa.base.TestBase">
    <skipped/>
  </testcase> <!-- setup_Browser -->
  <testcase name="setup_Browser" classname="com.jbk.qa.base.TestBase">
    <skipped/>
  </testcase> <!-- setup_Browser -->
  <testcase name="setUp" classname="com.jbk.qa.base.TestBase">
    <skipped/>
  </testcase> <!-- setUp -->
  <testcase name="setUp" classname="com.jbk.qa.base.TestBase">
    <skipped/>
  </testcase> <!-- setUp -->
  <testcase name="CloseApplication" classname="com.jbk.qa.base.TestBase">
    <skipped/>
  </testcase> <!-- CloseApplication -->
  <testcase name="CloseApplication" classname="com.jbk.qa.base.TestBase">
    <skipped/>
  </testcase> <!-- CloseApplication -->
</testsuite> <!-- com.jbk.qa.testcases.LoginPageTest -->
